### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#1]
Hi Team,

We already decided our team name; but we still need a project name.

So I made some research; i was thinking about memory, memento and memento mori; which are already used in various projects.

So I decided to use word : memoriae latin version of memory; however this is a team work and i need you suggestions. Soon we can make a poll and decide.

What do you guys think?

**Comment by ardaogulcan** [comment]
I guess we have decided our project as memoriae therefore I am closing this issue.
