### ISSUE TITLE
Copying the tasks to GitHub

### ISSUE THREAD

**Issue by mustafagonul** [574BandOfBrothers/memoriae#13]
Bahattin has done great work about creating tasks with using Trello. I think we should copy these to GitHub.

https://trello.com/b/VYYw7PP4

**Comment by mustafagonul** [comment]
I think, we can close this issue. AFAIK all issues created at Trello side is copied to Github.

**Comment by bahattinunal** [comment]
No more Trello. I will be adding the remaining tasks here from now on.
