### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#15]
As Arda suggested we will be desiging a mockup using marvelapp:

https://marvelapp.com

I already opened a user.

**Comment by fatiharaci** [comment]
Hi Team,

I made a mockup for our project;

https://marvelapp.com/6ec96cb

Please check and give your comments.

**Comment by ardaogulcan** [comment]
@fatiharaci I've documented your mockups in our wiki page https://github.com/574BandOfBrothers/memoriae/wiki

**Comment by fatiharaci** [comment]
Our mockup is not clear enough needs enhancement; the issue will be updated after the new requirements and mockup.

**Comment by bahattinunal** [comment]
We completed the requirements. I think it's time to update mockups.

**Comment by fatiharaci** [comment]
Mockup can be found here: 
https://github.com/574BandOfBrothers/memoriae/wiki/Mockup
