### ISSUE TITLE
Living History Examples

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#18]
Ask real people about their memories without mentioning the app; ask couple and listen them. Then record the idea to create examples.

**Comment by bahattinunal** [comment]
we should gather all our talks to a document and upload it somewhere visible.

**Comment by mustafagonul** [comment]
If this issue is done, please close :+1: 

@fatiharaci

**Comment by fatiharaci** [comment]
This examples will be shared thorud live API for presentation
