### ISSUE TITLE
Project Tools

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#2]
Please share the tools you suggest. We need a project plan soon.

**Comment by mustafagonul** [comment]
I think we should choose the tools, everyone in the team can use, so that all team members can make contributions. I have used django before, it was very easy to use, but to build complicated web apps, using html css and javascript becomes an obligation.

**Comment by mustafagonul** [comment]
We should build our app web based which has also mobile support. So if preparing a mobile application becomes a requirement, we can develop or find an application views our web application as a browser.

**Comment by mustafagonul** [comment]
@ardaogulcan You can make some suggestion regarding the tools we use in the project. As I know you are the best regarding the issue. We need a head start to make some contribution to the project.

**Comment by ardaogulcan** [comment]
Our tools may vary according to our applications requirements but I still have some common suggestions

**Infrastructure**

Apart from our application we may use AWS for our main infrastructure. It will provide us easy to use and scalable tools for all kinds of needs. We may use S3 for object storage, and use EC2 for our build server, application server etc. If we need server less architecture we may use AWS Lambda with API Gateway. It also provides RDS and DynamoDB for different database needs.

**Development Environment**

As we all will be developing, we need a solid development and production environments and we should use proper branching strategies for our source repos. For this we may use GitFlow branching, you can find an article about git branching in [here](http://nvie.com/posts/a-successful-git-branching-model/). 

We may also use Jenkins as our automation server we may automate our builds.

**Application**

As our requirements not clear yet, it is not easy to decide what to use. But we can check graph database providers, especially http://graph.cool which both provides database and restful api for this database by using this approach we may bypass writing an api code. If we need to, I recommend using Node.js as I am familiar with it and it is easy to learn and implement. We will be using Javascript for our frontend and mobile applications anyway so everybody will eventually learn javascript. Therefore, using same technology for all parts of application may be better for us.

**Comment by mustafagonul** [comment]
I think we can close this issue. @fatiharaci @ardaogulcan @battinunal @metepinar @korem7

**Comment by fatiharaci** [comment]
FrontEnd-Memoriae-APP:
https://github.com/574BandOfBrothers/memoriae/wiki/Development-Tools-for-Frontend-(Memoriae-APP)

**Comment by fatiharaci** [comment]
BackEnd-Memoriae-API:
https://github.com/574BandOfBrothers/memoriae/wiki/Development-Tools-for-Backend-(Memoriae-API)
