### ISSUE TITLE
Setup EC2 Instance for the Development Environment

### ISSUE THREAD

**Issue by ardaogulcan** [574BandOfBrothers/memoriae#23]
AWS (Amazon Web Services) EC2 (Elastic Compute Cloud) instance should be created and configured to serve Node.js application and Mongodb.

Requirements

- EC2 instance should be created in EU-West region
- Security zone should be configured to accept incoming and outgoing requests.
- Ngnix, Node, Mongodb should be installed and each of them should be run with assigned users.
- Ngnix Server should catch incoming request to port 80 and transfers to the Node server which runs on different port
- Mongodb shouldn't be accessible from outside.

**Comment by bahattinunal** [comment]
Got the AWS EC2 Ready in EU-West. Waiting for deployment. @ardaogulcan @fatiharaci

**Comment by bahattinunal** [comment]
Deployment is done. Waiting for caches to clear.
