### ISSUE TITLE
Setup CI Environment for development

### ISSUE THREAD

**Issue by ardaogulcan** [574BandOfBrothers/memoriae#25]
Continuous integration environment should be prepared.

Requirements

- Setup Jenkins for automation server.
- Configure Jenkins to check pull requests
- Configure Jenkins to deploy after merge

**Comment by bahattinunal** [comment]
This is done after the deployment i guess. @ardaogulcan shouldn't we close this one?

**Comment by ardaogulcan** [comment]
Ci environment created under

http://ci.memoriae.online
