### ISSUE TITLE
Package Installation Problem

### ISSUE THREAD

**Issue by bahattinunal** [574BandOfBrothers/memoriae#28]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2

**Comment by korem7** [comment]
It is only needed when the project is run on MacOS.
Ref: Stackoverflaw https://stackoverflow.com/a/40464936

**Comment by bahattinunal** [comment]
@ardaogulcan opinion? mac'e haftaya gecis yapıyorum su an linuxta ilerliyoruz.

**Comment by mustafagonul** [comment]
You can totally ignore this warning :+1: 
We can deal this warning later.

**Comment by bahattinunal** [comment]
Closing the issue for now.
