### ISSUE TITLE
Error with 3T studio mongoDB

### ISSUE THREAD

**Issue by bahattinunal** [574BandOfBrothers/memoriae#31]
(Studio 3T:13784): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

** (Studio 3T:13784): CRITICAL **: atk_object_initialize: assertion 'ATK_IS_OBJECT (accessible)' failed
Oct 28, 2017 5:42:39 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
Oct 28, 2017 5:42:40 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
Oct 28, 2017 5:42:40 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Opened connection [connectionId{localValue:1, serverValue:1}] to localhost:27017
Oct 28, 2017 5:42:40 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=2952403}
Oct 28, 2017 5:42:40 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Opened connection [connectionId{localValue:2, serverValue:2}] to localhost:27017

(Studio 3T:13784): GLib-CRITICAL **: Source ID 3120 was not found when attempting to remove it

**Comment by fatiharaci** [comment]
Hi Bahattin;

I have the same problem while creating a dev env mongoDB

com.mongodb.MongoSocketOpenException: Exception opening socket

**Comment by fatiharaci** [comment]
![image](https://user-images.githubusercontent.com/17599008/32136337-aa8721b6-bc14-11e7-8fee-81520abd9f7e.png)

**Comment by fatiharaci** [comment]
Hi Team,

I guess I found the solution; instead of basic connection select using URI solves the connection problem:

https://studio3t.com/whats-new/connect-hosted-mongodb-database/

For example for my setup:
**mongodb://localhost:27017/myproject**
mongodb:// is the protocol definition
localhost:27017 is the server we are connecting to
/myproject is the database we wish to connect to


Now I can connect via studio3T

**Comment by fatiharaci** [comment]
![image](https://user-images.githubusercontent.com/17599008/32163085-3148bf40-bd6c-11e7-94d5-2e0e76ac76ae.png)

**Comment by mustafagonul** [comment]
If you have any problems UI dependent, you can use **Robomongo**. I am currently using that application if I need a UI.

**Comment by fatiharaci** [comment]
@ardaogulcan could you please approve this; I guess we can close this issue.

**Comment by ardaogulcan** [comment]
i don't get the problem ? If it is related to your environment setup and you have figured it out we may close this one.

**Comment by bahattinunal** [comment]
I hate windows.
