### ISSUE TITLE
User API Development

### ISSUE THREAD

**Issue by mustafagonul** [574BandOfBrothers/memoriae#32]
Within this task user API necessary for the application shall be developed.

**Comment by ardaogulcan** [comment]
We may consider this one as a story and divide into different tasks,

Creating User Schema;
#35

Creating User Endpoint
#36

**Comment by mustafagonul** [comment]
Additional Tasks

Authentication API
#54 

JWT support for APIs
#55

**Comment by fatiharaci** [comment]
User API endpoint is now accesible we can close this issue now
