### ISSUE TITLE
Document GitHub repository 

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#4]
with at least the following information:

  a. An introduction that describes your project (including that it is a course project in software engineering)
  b. Summary and resources related to web annotation
  c. Description of annotation related tools and use cases that you found.

**Comment by ardaogulcan** [comment]
I have created the index page for Memoriae. @fatiharaci you may also document your presentation in the wiki page, this will be good for all of us as you have done such a good work to understand what an annotation is. Right now I am closing this issue. We should document this Wiki page in according to our project and we should open specific documentation tasks for each job.

https://github.com/574BandOfBrothers/memoriae/wiki
