### ISSUE TITLE
Uploads Endpoint Development

### ISSUE THREAD

**Issue by ardaogulcan** [574BandOfBrothers/memoriae#49]
Uploads endpoint should be created to manage AWS Uploads. SignedUrl method should be used for secure file uploads to the s3 directly from mobile app. To provide this api should pre sign and share upload url with mobile clients.

http://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-presigned-urls.html 

GET /uploads/request

**Comment by fatiharaci** [comment]
Following PR closes this issue:

https://github.com/574BandOfBrothers/memoriae-app/commit/4db74256d2ff395da28731660cba2e66f726d4c6
