### ISSUE TITLE
Missing Annotation Endpoints Should Be Created

### ISSUE THREAD

**Issue by ardaogulcan** [574BandOfBrothers/memoriae#50]
We have some missing endpoints for annotation model. Right now, Get annotations, Get annotation with id and Post annotation endpoints are ready. We need following endpoints;

- Paging Support -> https://www.w3.org/TR/annotation-protocol/#annotation-pages
- Update Support -> https://www.w3.org/TR/annotation-protocol/#update-an-existing-annotation
- Delete Support -> https://www.w3.org/TR/annotation-protocol/#delete-an-existing-annotation

**Comment by fatiharaci** [comment]
@mustafagonul could you please update the current status

**Comment by fatiharaci** [comment]
All Annotation enpoints are now deployed. You can check api commits and following documentation:

https://github.com/574BandOfBrothers/memoriae/wiki/API-Endpoints
