### ISSUE TITLE
Sign In-Up Screen  

### ISSUE THREAD

**Issue by ardaogulcan** [574BandOfBrothers/memoriae#51]
**Welcome Screen**

- If users are not authenticated a Welcome Screen with sign-in and sign-up button should present.
- Users should be able to sign-up with following information 
  - Name (At least 3 characters)
  - Email (Valid email)
  - Password (Should be validated with second inout)
  - Birthday (Proper Date)
- All fields must be validated on client before api request.

Authentication should be provided by /users endpoint of memoriae.
 - Access Token of authenticated users should be stored on local device to remember users.
 - Refresh Token of authenticated users should be stored on local device to refresh access token when expired

**Comment by fatiharaci** [comment]
First version is ready to deploy making tests.

**Comment by fatiharaci** [comment]
Folllowing PR closes this issue

https://github.com/574BandOfBrothers/memoriae-app/commit/b90f05b44982fbad3a7428ff645e2c77cb975971
