### ISSUE TITLE
Stories Screen

### ISSUE THREAD

**Issue by ardaogulcan** [574BandOfBrothers/memoriae#52]
**Stories Screen**
- Stories screen should be the landing screen on Tab Navigation if user is authenticated.
- All stories should be listed on stories screen in descending order.
- FlatList should be used to list stories
- User should be able to navigate the story detail by taping to the story item
- If story has media items, first media may be used for cover image
- If story is text based its title should be listed as story item

- /stories endpoint of memoriae should be used

**Comment by bahattinunal** [comment]
this looks line done? do we have anything to add here @ardaogulcan ?

**Comment by fatiharaci** [comment]
following PR closes this issue 

https://github.com/574BandOfBrothers/memoriae-app/pull/3
