### ISSUE TITLE
Create Story Screen

### ISSUE THREAD

**Issue by ardaogulcan** [574BandOfBrothers/memoriae#53]
Create Story Screen Should be created.

Following fields should be available on screen;

- title: TextInput, at least 2 characters maximum 200 characters long
- tags: TextInput, user should be able to input comma separated tags
- body: TextInput(multiline), textual body for story
- media:
  - Users should be able to upload images for story
  - Media Input should be consist of media previews and add image button
  - Media uploads should be handled by client
    - To upload files, client should request signed url from api
    - After receiving the signed url, client should post multipart request to the signed url.

**Comment by fatiharaci** [comment]
following PR closes this issue:

https://github.com/574BandOfBrothers/memoriae-app/pull/3
