### ISSUE TITLE
Create Project Plan

### ISSUE THREAD

**Issue by korem7** [574BandOfBrothers/memoriae#56]
We need to determine tasks.

**Comment by mustafagonul** [comment]
If this issue is done, please close :+1: 

@korem7 
@fatiharaci

**Comment by korem7** [comment]
We will review.

**Comment by fatiharaci** [comment]
@korem7 could you update the current status

**Comment by bahattinunal** [comment]
isn't this finished?

**Comment by korem7** [comment]
We used agile/kanbanboard for planning.
