### ISSUE TITLE
Creating Text Annotations Upon Existing Stories 

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#59]
Our annotations API is working and giving required responses.

We need to develop application interface for text annotations

**Comment by bahattinunal** [comment]
@mustafagonul @ardaogulcan can you guys tell me where can i get the auth token after user has logged in. @fatiharaci

**Comment by fatiharaci** [comment]
this is not yet implemented due to faster development; following issue is created for tracking:
#70

**Comment by fatiharaci** [comment]
This commit closes this issue:

https://github.com/574BandOfBrothers/memoriae-app/tree/feature/annotation-create-view-list
