### ISSUE TITLE
Create a list of question for requirements elicitation to be performed on 03.10.2017

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#6]

**Comment by metepinar** [comment]
Prepared a tentative Requirements Elicitation Questions page in the wiki section.

Next iteration would be the elicitation for a greenfield application, which has no system-as-is so elicitation questions would be guided to convert analog annotation and search to a digital one. Better be ready for both scenarios. A third scenario would be the complete removal of current digital system in favor of ours.

There is also a non-functional requirements quality factors trade-off list in the pipeline. It is hard to tell right now whether those qualities of the system-to-be should be elicited at this point in time but regardless, I am adding them just to inform the team of the possibilites of "How Well" aspect of the system other than "What", "Who" and "When" aspects.

**Comment by mustafagonul** [comment]
We have completed the issue? I guess we can close that.

**Comment by fatiharaci** [comment]
https://github.com/574BandOfBrothers/memoriae/wiki/Requirements
https://github.com/574BandOfBrothers/memoriae/wiki/Requirements-Elicitation
