### ISSUE TITLE
Add Location to History Items

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#63]

**Comment by fatiharaci** [comment]
@ardaogulcan have a question

normally we create history objects via dynamic Map object as follows:

```
    this.state = {
      story: Map({
        title: '',
        time: '',
        tags: '',
        body: '',
        location: '',
      }),
      images: List([]),
    };
  }
```

so adding a new parameter should not be an issue however backend seems to be missing this information:


`  console.log('actions/stories.js icindeki createStory' + JSON.stringify(fields, null, 4))
`

![image](https://user-images.githubusercontent.com/17599008/33803525-9bb318c4-dda3-11e7-8a8f-bf254505d8e2.png)

**Comment by fatiharaci** [comment]
![image](https://user-images.githubusercontent.com/17599008/33803542-ebc5d004-dda3-11e7-9fbc-4c5638d28b4e.png)

**Comment by fatiharaci** [comment]
HERE IS THE BACKEND RESPONSE:

```
    {
        "_id": "5a2cfaae741e390da83b38a1",
        "updatedAt": "2017-12-10T09:13:18.967Z",
        "createdAt": "2017-12-10T09:13:18.967Z",
        "title": "T1",
        "time": "D1",
        "body": "A1",
        "__v": 0,
        "comments": [],
        "media": [],
        "tags": [
            "T1"
        ]
    },
```

**Comment by fatiharaci** [comment]
@mustafagonul  need your help about the backend do we need to change DB?

**Comment by ardaogulcan** [comment]
@fatiharaci You should add new field to Mongoose Schema in API 

You should modify memoriae-api->src->models->story.js and add location field

**Comment by fatiharaci** [comment]
@mustafagonul could you make this change for me please

**Comment by fatiharaci** [comment]
https://github.com/574BandOfBrothers/memoriae-app/commit/fdcf3bef5bf9d004f9dae5f9dfa3e6d9fc1f0c55

this commit solves this issue
