### ISSUE TITLE
Github Projects vs Trello

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#7]
Hi Team,

Thanks to Bahattin we now have a trello page; however trello does not take issues from github automatically.

What do you think is it worth spending time by re-opening issues on Trello? Depending on this topic i will create a project in github or we will continue with trello.

http://www.easypolls.net/poll.html?p=59c928dae4b09f59c5b8b4de
--

**Comment by bahattinunal** [comment]
It seems that Trello only results in redundancy for us now. I think it's better to go with GitHub project at the moment not waste time and lose our focus.
