### ISSUE TITLE
Personal Logging

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#8]
Hi Team,

As each member needs a personal logging tool; I created a twitter page for the project and started logging. I think it is really practical. You can share your personal logs; so we can create a wiki page about it.

**Comment by fatiharaci** [comment]
My logging twitter account: https://twitter.com/MemoriaeLog_FA

**Comment by bahattinunal** [comment]
Apart from the private logs i'm keeping tailored and publicly accessible one is the twitter account. https://twitter.com/MemoriaeLog_BU

**Comment by metepinar** [comment]
Personal logs are generated here:
https://twitter.com/MemoriaeLog_MP

**Comment by fatiharaci** [comment]
https://twitter.com/MemoriaeLog_MP this account is private mete could you change it

**Comment by metepinar** [comment]
Fixed it, should be working now.
