### ISSUE TITLE
HW1 3. Include your team mates and me in your project team.

### ISSUE THREAD

**Issue by metepinar** [574BandOfBrothers/memoriae#9]
Collaborator request was sent using Settings->Collaborators->Insert user name of instructor->Add Collaborators. Leave this issue open until instructor accepts the invite.

**Comment by fatiharaci** [comment]
This issue has already been opened and closed; we are waiting for uskudarli's response:

Please check issue 5; this issue is now closed.

![image](https://user-images.githubusercontent.com/17599008/30860586-4c994e9c-a2d0-11e7-9230-7b99f9c736dc.png)
